/*
 * FormPersonal.java
 *
 * Created on June 14, 2004, 10:29 AM
 */

package prsUI;
import persistent.*;
import java.sql.*;
import java.util.*;
import javax.swing.*;
import java.text.*;
import javax.swing.text.*;
import java.math.BigDecimal;
/**
 *
 * @author  Andy
 */
public class FormClientiImobile extends javax.swing.JFrame {
    private Connection conn;
    private List sursaDateClienti;
    
    /** Creates new form FormPersonal */
    public FormClientiImobile() throws Exception {
        conn = Utilitati_.getConnection();
        sursaDateClienti= Clienti.getObjects(conn,null);        
        initComponents();

        
      DefaultComboBoxModel modelCboClienti = new DefaultComboBoxModel(sursaDateClienti.toArray());
      cboClienti.setModel(modelCboClienti);
                 this.formatGUIElements();
                for(int i=1;i<=12;i++)
            
      cboClienti.setSelectedIndex(0);
      this.setSize(600,600);
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        cboClienti = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        txtCnpcl = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAdresa = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNumecl = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        cmdPrevious = new javax.swing.JButton();
        cmdNext = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblImobile = new javax.swing.JTable();
        cmdAddImobil = new javax.swing.JButton();
        cmdStergeImobil = new javax.swing.JButton();
        cmdSalveazaImobil = new javax.swing.JButton();
        cmdRenunta = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCodpost = new javax.swing.JFormattedTextField();
        txtTelfix = new javax.swing.JFormattedTextField();
        txtTelmobil = new javax.swing.JFormattedTextField();
        txtTelbirou = new javax.swing.JFormattedTextField();
        txtCalitate = new javax.swing.JFormattedTextField();

        getContentPane().setLayout(null);

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        cboClienti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboClientiActionPerformed(evt);
            }
        });

        getContentPane().add(cboClienti);
        cboClienti.setBounds(50, 10, 120, 41);

        jLabel1.setText("Cnpclient");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 90, 60, 15);

        txtCnpcl.setEnabled(false);
        getContentPane().add(txtCnpcl);
        txtCnpcl.setBounds(100, 90, 120, 21);

        jLabel2.setText("Adresa");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 150, 40, 15);

        txtAdresa.setEnabled(false);
        getContentPane().add(txtAdresa);
        txtAdresa.setBounds(100, 150, 120, 21);

        jLabel3.setText("Codpost");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 180, 50, 15);

        jLabel4.setText("Tel fix");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(270, 90, 40, 15);

        jLabel5.setText("Nume Client");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 120, 70, 15);

        txtNumecl.setEnabled(false);
        getContentPane().add(txtNumecl);
        txtNumecl.setBounds(100, 120, 120, 21);

        jLabel6.setText("Tel mobil");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(270, 120, 50, 15);

        cmdPrevious.setText("<");
        cmdPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPreviousActionPerformed(evt);
            }
        });

        getContentPane().add(cmdPrevious);
        cmdPrevious.setBounds(240, 20, 39, 23);

        cmdNext.setText(">");
        cmdNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdNextActionPerformed(evt);
            }
        });

        getContentPane().add(cmdNext);
        cmdNext.setBounds(300, 20, 40, 23);

        tblImobile.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblImobile);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 300, 440, 110);

        cmdAddImobil.setText("Adauga linie");
        cmdAddImobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAddImobilActionPerformed(evt);
            }
        });

        getContentPane().add(cmdAddImobil);
        cmdAddImobil.setBounds(20, 440, 110, 23);

        cmdStergeImobil.setText("Sterge linie");
        cmdStergeImobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdStergeImobilActionPerformed(evt);
            }
        });

        getContentPane().add(cmdStergeImobil);
        cmdStergeImobil.setBounds(150, 440, 110, 23);

        cmdSalveazaImobil.setText("Salveaza pontaje");
        cmdSalveazaImobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSalveazaImobilActionPerformed(evt);
            }
        });

        getContentPane().add(cmdSalveazaImobil);
        cmdSalveazaImobil.setBounds(280, 440, 120, 23);

        cmdRenunta.setText("Renunta");
        cmdRenunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRenuntaActionPerformed(evt);
            }
        });

        getContentPane().add(cmdRenunta);
        cmdRenunta.setBounds(410, 440, 100, 23);

        jLabel7.setText("Tel Birou");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(274, 150, 50, 15);

        jLabel8.setText("Calitate");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(280, 180, 40, 15);

        txtCodpost.setEnabled(false);
        getContentPane().add(txtCodpost);
        txtCodpost.setBounds(100, 180, 120, 21);

        txtTelfix.setEnabled(false);
        getContentPane().add(txtTelfix);
        txtTelfix.setBounds(330, 90, 110, 21);

        txtTelmobil.setEnabled(false);
        getContentPane().add(txtTelmobil);
        txtTelmobil.setBounds(330, 120, 110, 21);

        txtTelbirou.setEnabled(false);
        getContentPane().add(txtTelbirou);
        txtTelbirou.setBounds(330, 150, 110, 21);

        txtCalitate.setEnabled(false);
        getContentPane().add(txtCalitate);
        txtCalitate.setBounds(330, 180, 110, 21);

        pack();
    }//GEN-END:initComponents

    private void cmdRenuntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRenuntaActionPerformed
       ModelJTableImobile model=(ModelJTableImobile)tblImobile.getModel();
       model.anulezModificari();
       tblImobile.revalidate();
       tblImobile.repaint();
    }//GEN-LAST:event_cmdRenuntaActionPerformed

    private void cmdStergeImobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdStergeImobilActionPerformed
       ModelJTableImobile model=(ModelJTableImobile)tblImobile.getModel();
       if (tblImobile.getSelectedRow()!=-1){
           model.stergLinie(tblImobile.getSelectedRow());
           model.comiteModificari();
           tblImobile.revalidate();
           tblImobile.repaint();
           
       }
    }//GEN-LAST:event_cmdStergeImobilActionPerformed

    private void cmdSalveazaImobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSalveazaImobilActionPerformed
        ModelJTableImobile model = (ModelJTableImobile) tblImobile.getModel();
        model.comiteModificari();
        tblImobile.revalidate();
        tblImobile.repaint();
    }//GEN-LAST:event_cmdSalveazaImobilActionPerformed

    private void cmdAddImobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAddImobilActionPerformed
       Clienti clienti = (Clienti) cboClienti.getSelectedItem();
       ModelJTableImobile model=(ModelJTableImobile)tblImobile.getModel();
       model.addLinieNoua(clienti.getcodcl());
       tblImobile.revalidate();
       tblImobile.repaint();
    }//GEN-LAST:event_cmdAddImobilActionPerformed

    private void cmdNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdNextActionPerformed
       int indexCurent = cboClienti.getSelectedIndex();
       if (indexCurent < cboClienti.getItemCount()-1)       
           cboClienti.setSelectedIndex(indexCurent+1);
       else
           JOptionPane.showMessageDialog(this,"Ai ajuns la ultima inregistrare!");       
    }//GEN-LAST:event_cmdNextActionPerformed

    private void cboClientiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboClientiActionPerformed
      //Clienti clienti = (clienti)cboClienti.getSelectedItem();
      //this.refreshFormular(ClientiImobile);
    }//GEN-LAST:event_cboClientiActionPerformed

    private void cmdPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPreviousActionPerformed
        int indexCurent = cboClienti.getSelectedIndex();
       if (indexCurent > 0)
           cboClienti.setSelectedIndex(indexCurent-1); 
       else
           JOptionPane.showMessageDialog(this,"Ai ajuns la prima inregistrare!");  
    }//GEN-LAST:event_cmdPreviousActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
        UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        new FormClientiImobile().show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboClienti;
    private javax.swing.JButton cmdAddImobil;
    private javax.swing.JButton cmdNext;
    private javax.swing.JButton cmdPrevious;
    private javax.swing.JButton cmdRenunta;
    private javax.swing.JButton cmdSalveazaImobil;
    private javax.swing.JButton cmdStergeImobil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblImobile;
    private javax.swing.JFormattedTextField txtAdresa;
    private javax.swing.JFormattedTextField txtCalitate;
    private javax.swing.JFormattedTextField txtCnpcl;
    private javax.swing.JFormattedTextField txtCodpost;
    private javax.swing.JFormattedTextField txtNumecl;
    private javax.swing.JFormattedTextField txtTelbirou;
    private javax.swing.JFormattedTextField txtTelfix;
    private javax.swing.JFormattedTextField txtTelmobil;
    // End of variables declaration//GEN-END:variables
        private void formatGUIElements(){
       // date calendaristice:
       java.text.SimpleDateFormat formatData=new java.text.SimpleDateFormat("dd/MM/yyyy");
       formatData.setLenient(false);
         // campuri numerice:
       java.text.DecimalFormat formatInt=new java.text.DecimalFormat("#");
       formatInt.setMinimumFractionDigits(0);
       formatInt.setMaximumIntegerDigits(5);
           
              // modelul gridului
       this.tblImobile.setModel(new ModelJTableImobile(conn));
       // rendere si editoare pentru coloanele gridului
        // coloanele numerice:
       java.text.DecimalFormat formatcodimobil=new java.text.DecimalFormat("#");
       java.text.DecimalFormat formatNumeric=new java.text.DecimalFormat("#.#");
       formatNumeric.setMinimumFractionDigits(0);
       formatNumeric.setMaximumIntegerDigits(2);
       
       this.tblImobile.setDefaultRenderer(BigDecimal.class, new FormattedRenderer(formatcodimobil));
       this.tblImobile.setDefaultEditor(BigDecimal.class, new FormattedEditor(formatcodimobil));       

    }
}   